#!/usr/bin/env python3
"""Does a company name's dictionary valence leak into how an LLM describes the company,
and can a single answer see it?

BACKGROUND. Peec AI (Ehrlinspiel, August 2026) scored 904 real brands on 5 assistants and
found that an 11% more positive brand name yields a 0.8% more positive description, with the
effect confined to brands the models do not recognise. They score descriptions against
Warriner, Kuperman and Brysbaert (2013), 13,915 English words rated 1 to 9 for valence. This
study uses the same norms so the numbers are directly comparable.

WHAT THIS ADDS. Three things their design cannot answer.

  1. NOISE FLOOR. They report one number per brand. A single LLM answer is a draw from a
     distribution, and our own variance-components work (arXiv:2607.13304) puts the
     reliability of a single-answer brand ranking near 0.01. So: run every name many times,
     measure the between-iteration spread of description valence, and ask whether an effect
     of the size they report is visible at n=1 at all. Then say how many rolls it takes.

  2. PSEUDOWORD CONTROL. They observe that the model "sometimes describes the word and not
     the company" and give examples. A control turns that observation into a test. For every
     real-word name there is a pseudoword of the same length and near-identical phonology,
     generated by a single documented consonant substitution and verified absent from both the
     valence norms and the system dictionary. If valence transfers for `Poison Inc.` and not
     for `Poisom Inc.`, the mechanism is lexical lookup, demonstrated rather than asserted.

  3. CROSS-LINGUAL ARM. The same concept as a Polish word, with the prompt still in English.
     `Trucizna Inc.` means poison to a reader of Polish and is an opaque string to everyone
     else. If valence transfers here too, the models are doing cross-lingual semantics on a
     brand name, which is a stronger claim than the English-only one and one nobody has
     tested. If it does not transfer, we have located the boundary of the effect.

DESIGN. 15 concepts spanning 5.11 points of the 1-to-9 valence scale, in three name
conditions (English word, pseudoword, Polish word), on two vendors, with n iterations each.
Web search is off, so this is the controlled arm.

    export GEMINI_API_KEY=... ANTHROPIC_API_KEY=...
    python3 probe.py --iterations 10
"""
import argparse, concurrent.futures, json, os, re, sys, threading, time
import urllib.error, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")

PROMPT = ("Describe the company {name} in exactly 10 single-word attributes. "
          "Return only a JSON array of 10 lowercase English words, nothing else.")

MODELS = [("gemini", "google", "gemini-2.5-flash"),
          ("claude", "anthropic", "claude-haiku-4-5-20251001"),
          ("gpt", "openai", "gpt-4.1-mini")]


class Failed(Exception):
    """The call did not return a usable list of ten attributes."""


def _post(url, payload, headers, timeout=90):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json", **headers})
    with urllib.request.urlopen(req, timeout=timeout) as fh:
        return json.load(fh)


def _parse(text):
    if not text:
        raise Failed("empty")
    m = re.search(r"\[.*\]", text, re.S)
    if not m:
        raise Failed("no complete array")
    try:
        arr = json.loads(m.group(0))
    except json.JSONDecodeError as e:
        raise Failed(f"unparseable: {e}")
    words = [re.sub(r"[^a-z]", "", str(x).lower()) for x in arr]
    words = [w for w in words if w]
    if len(words) < 5:
        raise Failed(f"only {len(words)} usable attributes")
    return words


def call_google(model, name):
    key = os.environ["GEMINI_API_KEY"]
    d = _post(f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}",
              {"contents": [{"parts": [{"text": PROMPT.format(name=name)}]}],
               "generationConfig": {"maxOutputTokens": 2048}}, {})
    cand = (d.get("candidates") or [None])[0]
    if not cand:
        raise Failed("no candidate")
    if cand.get("finishReason") not in (None, "STOP"):
        raise Failed(f"finishReason={cand['finishReason']}")
    return _parse("".join(p.get("text", "") for p in cand.get("content", {}).get("parts", [])))


def call_anthropic(model, name):
    d = _post("https://api.anthropic.com/v1/messages",
              {"model": model, "max_tokens": 2048,
               "messages": [{"role": "user", "content": PROMPT.format(name=name)}]},
              {"x-api-key": os.environ["ANTHROPIC_API_KEY"], "anthropic-version": "2023-06-01"})
    if d.get("stop_reason") not in (None, "end_turn", "stop_sequence"):
        raise Failed(f"stop_reason={d['stop_reason']}")
    return _parse("".join(b.get("text", "") for b in d.get("content", []) if b.get("type") == "text"))


def call_openai(model, name):
    d = _post("https://api.openai.com/v1/chat/completions",
              {"model": model, "max_tokens": 2048,
               "messages": [{"role": "user", "content": PROMPT.format(name=name)}]},
              {"Authorization": f"Bearer {os.environ['OPENAI_API_KEY']}"})
    ch = d["choices"][0]
    if ch.get("finish_reason") not in (None, "stop"):
        raise Failed(f"finish_reason={ch['finish_reason']}")
    return _parse(ch["message"]["content"])


VENDOR = {"google": call_google, "anthropic": call_anthropic, "openai": call_openai}


def ask(vendor, model, name):
    """Temperature is left at the vendor default. The point of this study is the spread of
    repeated answers, so pinning it to 0 would remove the quantity being measured. A failed
    call is recorded as a failure and never as an empty attribute list."""
    last = ""
    for attempt in range(3):
        try:
            return VENDOR[vendor](model, name), "ok"
        except Failed as e:
            last = str(e)
        except (urllib.error.URLError, urllib.error.HTTPError, KeyError, TimeoutError) as e:
            last = f"{type(e).__name__}: {str(e)[:90]}"
        time.sleep(1.5 * (attempt + 1))
    return [], f"failed: {last}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--iterations", type=int, default=10)
    ap.add_argument("--workers", type=int, default=8)
    a = ap.parse_args()

    for k in ("GEMINI_API_KEY", "ANTHROPIC_API_KEY"):
        if not os.environ.get(k):
            sys.exit(f"missing {k}")

    design = json.load(open(os.path.join(DATA, "name-design.json"), encoding="utf-8"))
    jobs = []
    for d in design:
        for cond, stem in (("en_word", d["en_word"]), ("pseudo", d["pseudo"]), ("pl_word", d["pl_word"])):
            for mid, vendor, model in MODELS:
                for it in range(a.iterations):
                    jobs.append({"concept": d["en_word"], "band": d["band"],
                                 "name_valence": d["valence"], "condition": cond,
                                 "company": f"{stem} Inc.", "model": mid,
                                 "vendor": vendor, "model_id": model, "iteration": it})
    print(f"{len(design)} concepts x 3 name conditions x {len(MODELS)} models x {a.iterations} iterations "
          f"= {len(jobs)} calls", flush=True)

    cache_path = os.path.join(DATA, "responses.jsonl")
    done = set()
    if os.path.exists(cache_path):
        for ln in open(cache_path, encoding="utf-8"):
            if ln.strip():
                r = json.loads(ln)
                done.add((r["company"], r["model"], r["iteration"]))
        print(f"  resuming, {len(done)} already collected")

    todo = [j for j in jobs if (j["company"], j["model"], j["iteration"]) not in done]
    lock = threading.Lock()
    n = {"done": 0, "failed": 0}

    def work(j, fh):
        attrs, status = ask(j["vendor"], j["model_id"], j["company"])
        rec = {**j, "attributes": attrs, "status": status}
        with lock:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
            fh.flush()
            n["done"] += 1
            n["failed"] += status != "ok"
            print(f"  {n['done']}/{len(todo)}  failures {n['failed']}", end="\r", flush=True)

    if todo:
        with open(cache_path, "a", encoding="utf-8") as fh:
            with concurrent.futures.ThreadPoolExecutor(max_workers=a.workers) as pool:
                list(pool.map(lambda j: work(j, fh), todo))
        print()
    print(f"wrote {cache_path}")


if __name__ == "__main__":
    main()
